spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ticket_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: cat010320..
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379



